services:
  web:
    build: .
    container_name: blog_web
    ports:
      - "8000:8000"
    env_file:
      - .env    # Загружаем переменные окружения из .env файла
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15 # Используем официальный образ PostgreSQL (можно выбрать другую версию)
    container_name: blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persistent data
    ports:
      - "${DB_PORT:-5432}:5432" # Используем порт из .env или 5432 по умолчанию
    environment:
      POSTGRES_DB: ${DB_NAME:-blog_db_project} # Имя БД из .env или значение по умолчанию
      POSTGRES_USER: ${DB_USER:-blog_user_project} # Пользователь из .env или значение по умолчанию
      POSTGRES_PASSWORD: ${DB_PASSWORD:-blog_password_project} # Пароль из .env или значение по умолчанию
    restart: unless-stopped

volumes:
  postgres_data: # Именованный volume для данных PostgreSQL 